apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: ibackend:v1
          imagePullPolicy: Never
          ports:
            - containerPort: 5000
          env:
           - name: DATABASE_HOST
             valueFrom:
              configMapKeyRef:
                name: variables
                key: DATABASE_HOST
           - name: DATABASE_NAME
             valueFrom:
              configMapKeyRef:
                name: variables
                key: DATABASE_NAME
           - name: DATABASE_USER
             valueFrom:
              configMapKeyRef:
                name: variables
                key: DATABASE_USER
           - name: DATABASE_PASSWORD
             valueFrom:
              configMapKeyRef:
                name: variables
                key: DATABASE_PASSWORD